version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: school_db
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
  web:
    build: .
    command: bash -c "python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:${PORT}"
    volumes:
      - .:/code
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - db

volumes:
  postgres_data: