# Generated by Django 3.2.12 on 2022-02-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentparent',
            unique_together={('parent', 'student')},
        ),
    ]
